CREATE TABLE TIPO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(40),
	PRIMARY KEY (ID)
);

CREATE TABLE FORNECEDOR(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(40),
	ENDERECO VARCHAR(40),
	CNPJ VARCHAR(30),
	PRIMARY KEY(ID)
);


CREATE TABLE PRODUTO (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(40),
	VALOR NUMERIC(10,2),
	VALIDADE DATE,
	FORNECEDOR INTEGER NOT NULL REFERENCES FORNECEDOR(ID),
	TIPO INTEGER NOT NULL REFERENCES TIPO(ID),
	PRIMARY KEY(ID)
);